[versions]
composePreviewLab = "0.1.0-dev09"
kotlin = "2.2.21"
compose = "1.10.0-rc02"
agp = "8.9.3"
androidx-activityCompose = "1.11.0"
androidx-uiTest = "1.9.4"
lumoUi = "1.2.5"
dokar3Sonner = "0.3.8"
hotReload = "1.1.0-alpha02"
ksp = "2.3.2"
intellijPlatform = "2.6.0"
jewelIdeLafBridge = "0.27.0"
kotlinxSerializationJson = "1.9.0"
vanniktechMavenPublish = "0.35.0"
dokka = "2.1.0"
binaryCompatibilityValidator = "0.18.1"
ktlint = "1.6.0"
ktlintGradle = "14.0.1"
androidxLifecycle = "2.9.6"
kodeview = "0.9.0"
kotest = "6.0.5"
kotlinxCoroutines = "1.10.1"
filekit = "0.12.0"

[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-uitest-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-uitest-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
dokar3Sonner = { module = "io.github.dokar3:sonner", version.ref = "dokar3Sonner" }

kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinCompilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kspApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
jewelIdeLafBridge = { module = "org.jetbrains.jewel:jewel-ide-laf-bridge-243", version.ref = "jewelIdeLafBridge" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktlintGradlePlugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintGradle" }
vanniktechMavenPublishGradlePlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktechMavenPublish" }
dokkaGradlePlugin = { module = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }
kspGradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
kotestProperty = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
filekitCore = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekitDialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }

androidxLifecycleViewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidxLifecycleRuntimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
kodeview = { module = "dev.snipme:kodeview", version.ref = "kodeview" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }
lumoUi = { id = "com.nomanr.plugin.lumo", version.ref = "lumoUi" }

ktlintGradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
conventionFormat = { id = "convention-format", version = "unspecified" }
conventionPublish = { id = "convention-publish", version = "unspecified" }
