name: Preview on Web
on:
  push:
    branches:
      - main

jobs:
  publish-dokka:
    name: Release dokka documentation
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Java for Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Resolve version from Gradle
        id: get_version
        run: echo "version=$(./gradlew -q logVersion)" >> "$GITHUB_OUTPUT"
      - name: Build Dokka Documentation
        run: ./gradlew :dokkaDocs:dokkaGenerate
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dokkaDocs/build/dokka/html
          destination_dir: dokka/${{ steps.get_version.outputs.version }}/
          keep_files: true

  deploy-web-documentation:
    name: Deploy Web Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java for Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Setup npm
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./integrationTest/web/package-lock.json
      - name: Setup safe-chain
        run: |
          npm i -g @aikidosec/safe-chain
          safe-chain setup-ci

      - run: mkdir -p ./public

      - name: Build publish wasmJs contents
        run: cd integrationTest && ./gradlew :app:buildProductionPreviewLabGallery
      - run: echo 'config.baseUrl = "/compose-preview-lab/integrationTest/main/js"' >> ./integrationTest/web/docusaurus.config.ts
      - run: cd integrationTest/web && npm ci && npm run build
      - run: cp -r ./integrationTest/web/build ./public/js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: integrationTest/main
